R3/T2 - Lista de opções parte inferior do perfil
disciplinas-prof-Edeilson-UFT/eng-soft-2021-2 pull request #45
Opened 2021-11-10 03:51 UTC by Rafael-jooj

2021-11-10 13:51 UTC, LindomarRodrigues requested changes
Você repetiu muitas vezes o mesmo trecho de código, seria preferível criar uma função para esse trecho que se repete várias vezes.

2021-11-10 13:51 UTC, LindomarRodrigues commented on lib/pages/perfil.dart
> -    with SingleTickerProviderStateMixin {
Você não pode fazer isso, vai gerar inconsistência na hora de implementar o `Redux`.

2021-11-10 13:51 UTC, LindomarRodrigues commented on lib/pages/perfil.dart
> +    return Scaffold(
Porque removeu o cabeçalho?
Enquanto ninguém fizer um mais completo pode ir mantendo esse mesmo

2021-11-10 13:51 UTC, LindomarRodrigues commented on lib/components/perfil/abas_inferiores_do_perfil.dart
> +          Container(
Isso não deveria estar aqui, isso é o cabeçalho e o seu componente não tem nenhuma relação com isso, nem vem imediatamente após.

Dessa forma fica impossível as outras pessoas posicionarem os seus elementos nos locais corretos.

2021-11-10 13:51 UTC, LindomarRodrigues commented on lib/components/perfil/abas_inferiores_do_perfil.dart
> +          Container(
Isso também não deve existir, pois irá fazer existir um espaço gigante entre o seu elemento e o anterior

2021-11-10 13:51 UTC, LindomarRodrigues commented on lib/components/perfil/abas_inferiores_do_perfil.dart
> +                Text(' Ajuda', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20, color: Colors.black45),),
A fonte poderia ter um Weight um pouco menor, da forma atual está muito mais forte do que realmente é no aplicativo original.

2021-11-10 13:52 UTC, LindomarRodrigues requested changes
A fonte também está um pouco maior do que deveria.

2021-11-10 13:57 UTC, LindomarRodrigues commented
Outra coisa é que falta adicionar o seu nome a branch

2021-11-11 04:10 UTC, Rafael-jooj commented on lib/pages/perfil.dart
> -    with SingleTickerProviderStateMixin {
Solicitações reparadas!

2021-11-11 11:38 UTC, LindomarRodrigues commented
Boa parte das alterações não foram feitas, basicamente apenas as visuais, que sinceramente são as menos relevantes.

"Você repetiu muitas vezes o mesmo trecho de código, seria preferível criar uma função para esse trecho que se repete várias vezes."

2021-11-11 15:27 UTC, merged