MESCLAGEM DE LEVANTAMENTO DE REQUISITOS GRUPO 01
disciplinas-prof-Edeilson-UFT/eng-soft-2021-2 pull request #7
Opened 2021-10-14 14:51 UTC by yarion1

- os requisitos foram levantados e adcionados a uma branch develop em formato markdown pelos membros do grupo.
- a branch develop foi mergida em uma branch main que esta sendo enviada neste pull.

2021-10-20 02:06 UTC, nnmf requested changes
1.: O título está errado e um tanto confuso, pois não está especificando de forma assertiva aquele caso de uso (Por exemplo, é para efetuar buscas sobre lojas de conveniência? Efetuar compra numa loja de conveniência? Lembrando que efetuar busca ou compra são DOIS casos de usos diferentes). Um título de caso de uso deve conter verbos, pois é um requisito funcional. Como por exemplo Buscar Produtos, Buscar Lojas de Conveniência, Efetuar Compras em Lojas de Conveniências, etc.

2.: Acerca da descrição do requisito, não está errado, mas de acordo com o que eu entendi do requisito eu sugiro algo como: “Em conveniência é possível efetuar compras de produtos em lojas de conveniências.” É mais e direto.

3.: Na pré-condição: Caso o objetivo do caso de uso seja apenas buscar em lojas de conveniências, as pré-condições estão válidas. Porém, caso seja efetuar compra deve-se colocar também como pré-requisito efetuar login no aplicativo.

4.: Acerca do fluxo principal: 
1.	Instalar (Do cliente) – Pode-se remover pois já está especificado na pré-condição
2.	Efetuar login no aplicativo (Do cliente) – Se o intuito do caso de uso é comprar, faça que nem com o 1º passo. Caso seja apenas buscar pelo produto de loja de conveniência não é necessário.
3.	Definir localização (Onde irá ser entregue o produto) – Não é necessário caso deseje apenas buscar.
4.	Acessar página a aba de Conveniências – Segue aqui uma mudança que sugiro: O Ator acessa a tela inicial do sistema e, assim, seleciona a aba de Conveniências.
5.	Selecionar um produto 
6.	Adicionar produto à sacola de compras 
7.	Efetuar compra – Lembrando, caso o caso de uso seja sobre buscar por lojas de conveniências, não é nescessário a parte efetuar compras pois, ela cai em outro requisito de uso: efetuar.

Sugestão de Fluxo Principal. Caso o Caso de Uso seja efetuar compra por lojas de conveniência:
1.	O Ator acessa a tela inicial do sistema
2.	Selecionar a aba de Conveniências
3.	Buscar e selecionar produto desejado
4.	Adicionar produto à sacola de compras
5.	Efetuar compra

5.: Verifique se o Geolocalizador será considerado ator (GPS é uma funcionalidade do sistema, do smartphone onde o app pede acesso). Sugiro mudar o Fazer cadastro para efetuar login, também, mudar extend para include (Pois só pode comprar caso seja efetuado login).

User Stories: o 1.0 pode ser removido, e substituído pelo 1.1 que está bom. O 1.2 deveria ser encaixado como fluxo alternativo, onde mostra sendo efetuada compra com ofertas de desconto. O 1.3 está bom também.

6.: Novamente caso o Caso de Uso seja acerca de efetuar compras, faltou apenas um print da tela de login e também faltou o print da tela de inserção de desconto (como descrito no User Stories). Uma sugestão que deixa a visualização melhor é o print da tela inteira.

2021-10-20 18:52 UTC, nhangamona approved these changes

2021-10-20 21:47 UTC, Mateus-Arauj requested changes
R2_Bebidas 
1. Observação sobre o título: Ser mais específico e objetivo, o título deve conter uma ação realizada pelo ator.

2021-10-21 03:16 UTC, Mateus-Arauj approved these changes

2021-10-24 23:53 UTC, merged